language: c

env:
    matrix:
        - hyperopt=dev     python=2
        - hyperopt=0.0.2   python=2
        - hyperopt=none    python=3

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - bash Miniconda-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH

  # install requirements file in python
  - conda create --yes -n test python=$python `cat requirements.txt | xargs`
  - source activate test
  # install extra dependency for style checking
  - conda install flake8
  # instal hyperopt dependencies
  - '[ "$hyperopt" != "none" ] && conda install --yes pymongo networkx || echo ""'
  # install hyperopt
  - '[ "$hyperopt" = "0.0.2" ] && conda install --yes pip && pip install hyperopt || echo ""'
  - '[ "$hyperopt" = "dev" ]   && git clone https://github.com/hyperopt/hyperopt.git && cd hyperopt && python setup.py -q install && cd - || echo ""'


script:
  - python setup.py install
  - nosetests -v
  # exclude versioneer.py and _version.py from style checking, since we don't
  # write/maintain them
  - flake8 `find . -name '*.py'  ! -name build ! -path './build/*' !
            -name versioneer.py ! -name _version.py | xargs`
