language: c

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - bash Miniconda-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH

  - conda install `cat requirements.txt | xargs`

  - git clone https://github.com/hyperopt/hyperopt.git
  - cd hyperopt
  - python setup.py install
  - cd ..

script:
  - python setup.py install
  - nosetests -v
