language: c

env:
    matrix:
        - hyperopt=dev     python=2
        - hyperopt=0.0.2   python=2
        - hyperopt=none    python=3

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - bash Miniconda-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH

  - '[ $python = 2 ] && conda install --yes `cat requirements.txt | xargs` || echo ""'
  - '[ $python = 3 ] && conda create --yes -n 3 python=3 `cat requirements.txt | xargs` && source activate 3 || echo ""'
  
  - '[ "$hyperopt" != "none" ] && conda install --yes pymongo networkx || echo ""'
  - '[ "$hyperopt" = "0.0.2" ] && conda install --yes pip && pip install hyperopt || echo ""'
  - '[ "$hyperopt" = "dev" ]   && git clone https://github.com/hyperopt/hyperopt.git && cd hyperopt && python setup.py -q install && cd - || echo ""'

script:
  - python setup.py install
  - nosetests -v
