language: c

env:
    matrix:
        - hyperopt=dev
        - hyperopt=0.0.2

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - bash Miniconda-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH

  - conda install --yes `cat requirements.txt | xargs`
  
  - conda install --yes pymongo networkx  # required for hyperopt
  - '[ $hyperopt = 0.0.2 ] && conda install --yes pip && pip install hyperopt || echo "skipping conda install hyperopt"'
  - '[ $hyperopt = dev ] && git clone https://github.com/hyperopt/hyperopt.git && cd hyperopt && python setup.py install && cd - || echo "skipping pip install hyperopt"'

script:
  - python setup.py install
  - nosetests -v
