estimator:
    # pickle: model.pickle
    eval: |
        Pipeline([
                ('featurizer', DihedralFeaturizer(types=['phi', 'psi'])),
                ('tica', tICA())
        ])

cv: 5

search:
    space:
        tica__n_components:
            min: 1
            max: 4
            type: float
    engine: hyperopt_tpe

dataset:
    trajectories: ~/local/msmbuilder/Tutorial/XTC/*/*.xtc
    topology: ~/local/msmbuilder/Tutorial/native.pdb
    stride: 1

trials:
    uri: sqlite:///foo.db
